### ISSUE TITLE
unable to run .js program

### ISSUE THREAD

**Issue by shekar1046** [Miramac/vscode-exec-node#27]
![image](https://user-images.githubusercontent.com/38904311/53207916-eb217000-35e9-11e9-85cd-473eb558c52f.png)

**Comment by ddeklerk28** [comment]
I have been experiencing the same issue. When a snippet or file is executed the first time it runs fine. In the output tab you see "Info: Start Process (...)" then output. But the process is never ended. Therefor if I try to execute using f8 again, I receive the "process is already running!" flag.

Edit: Only when VS Code is restarted, you can use f8 (only once since the initial process is never ended) and then the same problem repeats.

**Comment by Miramac** [comment]
which OS and VS Code version do you work with?

Thanks!

**Comment by ddeklerk28** [comment]
-Win 10 professional 64-bit
-VS Code 1.31.1

**Comment by kzjimmy** [comment]
The same mistake happened to me！

**Comment by mb2o** [comment]
Same issue here in Win10 with vscode insiders 1.32.0

**Comment by Miramac** [comment]
Thanks for all your reports. I have finally found the problem. I still used async functions without a callback. Due to the internal switching to node 10 in VSCode this is now a fatal error.

I will push a new version as soon as possible.

**Comment by AlessandroMelo88** [comment]
the same is happening to me on linux deepin

 win 10 is working
